name: Test Suite Workflow

# Trigger on push or pull request events
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    # Steps to run the test
    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Specify the version of Node.js you are using

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run Playwright tests
      - name: Run Playwright tests
        run: npx playwright install

      # Run Playwright tests
      - name: Run Playwright tests
        run: npx playwright test

      # Upload test artifacts (screenshots, videos, etc.)
      - name: Upload Playwright artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-artifacts
          path: playwright-report # Or the path to your Playwright artifacts directory

      # Publish test results
      - name: Publish test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results




